# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92b419259da5f46d4e2feb555972e5a79089ff4818bb8fe6a4ec2ba8de19e47ecb86a3b8d9b56e6f00ccc631354e101d754fc2ca83108a3fc838057ab5ac7dce

test:
  secret_key_base: bc6c02436bee53af9d0e2e8475f6ff835be09b6340e082a97fdf502a0fd2160d5cc8c48498979656235c3c199e0f05ac42e7fa4e22f752385ff81adaf97ef50a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
